# Configuration File for the Ip SLA Poller

# Poll Frequency in seconds
poll_frequency: 30

# Number of snmp processes to spawn, used to connect to devices and poll snmp data
number_of_snmp_processes: 3

# Number of ip sla's in each ipsla process
db_process_delay: 1

# Delay in seconds between the ipsla processing and the db inserting
number_of_db_processes: 1

# Database to use, choices: sqlite, mongodb
db: sqlite

# Database name
db_name: ipsla

# SNMP variables
snmp:
  # Timeout in seconds
  timeout: 2
  # Number of retries
  retries: 3

# MongoDB Info
mongo:
  host: 127.0.0.1
  port: 27017
  username: ipsla
  password: ipsla